#define IDEN 1
#define SUMA 2
#define REST 3
#define MULT 4
#define DIVI 5
#define IGUA 6
#define ENTE 7
#define PYCO 8
#define PARI 9
#define PARD 10
#define PRIN 11
#define CADN 12
#define COMA 13
#define LLAVI 14
#define LLAVD 15
#define MAIN 16